# Git-aware prompt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats ' (%b)'
setopt PROMPT_SUBST
export PROMPT='%n@%m %F{green}%~%F{yellow}${vcs_info_msg_0_}%f $ '
export CLICOLOR=1

# Conda (portable equivalent of the block generated by `conda init`)
CONDA_HOME="$HOME/miniforge3"
if [[ -x "$CONDA_HOME/bin/conda" ]]; then
  __conda_setup="$("$CONDA_HOME/bin/conda" shell.zsh hook 2>/dev/null)"
  if [[ $? -eq 0 ]]; then
    eval "$__conda_setup"
  elif [[ -f "$CONDA_HOME/etc/profile.d/conda.sh" ]]; then
    source "$CONDA_HOME/etc/profile.d/conda.sh"
  else
    export PATH="$CONDA_HOME/bin:$PATH"
  fi
  unset __conda_setup
fi

# Developer tools
export PATH="$HOME/.codeium/windsurf/bin:$PATH"
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"
export PATH="$HOME/.antigravity-ide/antigravity-ide/bin:$PATH"
export PATH="$HOME/.opencode/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.grok/bin:$PATH"
export PATH="/Library/PostgreSQL/18/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"

# Local environment generated by installers
[[ -f "$HOME/.local/bin/env" ]] && source "$HOME/.local/bin/env"

# Mamba
export MAMBA_EXE="$CONDA_HOME/bin/mamba"
export MAMBA_ROOT_PREFIX="$CONDA_HOME"
if [[ -x "$MAMBA_EXE" ]]; then
  __mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2>/dev/null)"
  if [[ $? -eq 0 ]]; then
    eval "$__mamba_setup"
  else
    alias mamba="$MAMBA_EXE"
  fi
  unset __mamba_setup
fi

# Grok completions
if [[ -d "$HOME/.grok/completions/zsh" ]]; then
  fpath=("$HOME/.grok/completions/zsh" $fpath)
  autoload -Uz compinit && compinit -C
fi

# Put secrets and machine-specific exports here; this file is gitignored.
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
